FROM node:24-alpine AS builder-frontend

RUN apk --no-cache add make

WORKDIR /app

COPY frontend ./frontend
RUN cd frontend && \
    npm ci

COPY Makefile ./
COPY assets ./assets
COPY views ./views

WORKDIR /app/frontend
ENTRYPOINT ["npm", "run", "dev"]

FROM golang:1.24.1-alpine AS builder-backend
ARG BUILD_TIME
ARG GIT_COMMIT
ARG GIT_REF
ARG GIT_REF_NAME
ARG GIT_REF_TYPE

RUN apk --no-cache add make

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY Makefile ./
COPY assets ./assets
COPY cmd ./cmd
COPY pkg ./pkg
COPY vendor ./vendor
COPY views ./views
COPY translations ./translations

ENTRYPOINT ["make", "dev-backend"]
